// P10 Task 3 (AC-P10-01) — Release packaging (TRD §13.2, PRD FR-801/FR-804/FR-805).
//
// Produces the v0.1.0 beta release directory:
//   release/tether-extension-<version>-chrome-mv3.zip   (lean-manifest store artifact)
//   release/daemon/ + release/tether-daemon.mjs         (daemon; bun binaries when bun exists)
//   release/store/                                      (CWS listing assets)
//   release/BINARIES.md                                 (only when bun is unavailable)
//   release/manifest.json                               { version, builtAt, artifacts[] }
//
// The whole release/ directory is gitignored (manifest included); artifact hashes
// are reproducible at any time by re-running this script (see docs/RELEASE.md §5).

import { execSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import {
  cpSync,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import { join, relative } from 'node:path';

const ROOT = process.cwd();
const RELEASE_DIR = join(ROOT, 'release');
const EXTENSION_DIR = join(ROOT, 'apps', 'extension');
const DAEMON_DIR = join(ROOT, 'apps', 'daemon');
const STORE_ASSETS = join(ROOT, 'apps', 'web', 'public', 'store');

const BUN_TARGETS = [
  { name: 'tether-daemon-darwin-arm64', target: 'bun-darwin-arm64' },
  { name: 'tether-daemon-linux-x64', target: 'bun-linux-x64' },
  { name: 'tether-daemon-windows-x64', target: 'bun-windows-x64' },
];

function run(cmd: string, cwd = ROOT, env: NodeJS.ProcessEnv = {}): void {
  console.log(`> ${cmd}`);
  execSync(cmd, { cwd, stdio: 'inherit', env: { ...process.env, ...env } });
}

function hasBun(): boolean {
  try {
    execSync('bun --version', { stdio: 'pipe' });
    return true;
  } catch {
    return false;
  }
}

function sha256File(file: string): string {
  return createHash('sha256').update(readFileSync(file)).digest('hex');
}

// Collect every artifact file under release/ (skipping the manifest itself).
function collectArtifacts(dir: string, base = dir, acc: string[] = []): string[] {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      collectArtifacts(full, base, acc);
    } else if (entry.isFile() && !full.endsWith('manifest.json')) {
      acc.push(full);
    }
  }
  return acc;
}

function writeManifest(version: string): void {
  const artifacts = collectArtifacts(RELEASE_DIR).map((file) => ({
    name: relative(RELEASE_DIR, file).replace(/\\/g, '/'),
    sha256: sha256File(file),
    bytes: statSync(file).size,
  }));
  artifacts.sort((a, b) => a.name.localeCompare(b.name));
  const manifest = {
    version,
    builtAt: new Date().toISOString(),
    artifacts,
  };
  writeFileSync(
    join(RELEASE_DIR, 'manifest.json'),
    `${JSON.stringify(manifest, null, 2)}\n`,
    'utf-8',
  );
  console.log(`manifest.json written (${artifacts.length} artifacts).`);
}

const NODE_LAUNCHER = `#!/usr/bin/env node
// Tether daemon launcher — generated by scripts/package-release.ts. Do not edit.
// Used when bun-compiled native binaries are not part of this release.
// Resolution order: ./daemon/index.js (offline layout), then installed @tether/daemon.
import { existsSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const localEntry = join(here, 'daemon', 'index.js');

if (existsSync(localEntry)) {
  await import(pathToFileURL(localEntry).href);
} else {
  const require = createRequire(import.meta.url);
  const pkgDir = dirname(require.resolve('@tether/daemon/package.json'));
  await import(pathToFileURL(join(pkgDir, 'dist', 'index.js')).href);
}
`;

const BINARIES_MD = (version: string): string => `# Daemon binaries — v${version}

> This release ships **no compiled native daemon binaries**: \`bun\` was not available
> on the release machine, so \`bun build --compile\` targets (darwin-arm64, linux-x64,
> windows-x64) were skipped (TRD §13.2, PRD FR-805 — installers are P1).

## Run the daemon anyway (beta testers)

1. Install Node.js **>= 20**.
2. From a checkout of this repository at the matching version: \`pnpm install\`.
3. Use the generated launcher from this directory:

   \`\`\`bash
   ./tether-daemon.mjs connect     # detect harnesses and write MCP configs
   ./tether-daemon.mjs serve       # start the loopback WS + MCP server
   \`\`\`

   The launcher resolves \`./daemon/index.js\` (copied here for offline use; needs the
   workspace \`node_modules\`) or the installed \`@tether/daemon\` package.

## Producing real binaries

On a machine with [bun](https://bun.sh) >= 1.1:

\`\`\`bash
pnpm install
pnpm --filter @tether/daemon build
for t in darwin-arm64 linux-x64 windows-x64; do
  bun build --compile --target=bun-\$t apps/daemon/src/index.ts \\
    --outfile release/tether-daemon-\$t
done
pnpm package-release
\`\`\`

The packager detects bun and embeds the three binaries instead of the launcher,
recording each one in \`manifest.json\` with its SHA-256.
`;

function packageExtension(version: string): void {
  // FR-102/HR-3: the store artifact must ship the lean manifest — <all_urls> as
  // optional_host_permissions only, no granted host_permissions, no broad permissions.
  run('pnpm --filter @tether/extension zip', EXTENSION_DIR, { TETHER_MANIFEST: 'lean' });
  const outDir = join(EXTENSION_DIR, '.output');
  const zips = readdirSync(outDir).filter((f) => f.endsWith('.zip'));
  if (zips.length === 0) throw new Error('wxt zip produced no .zip artifact');
  mkdirSync(RELEASE_DIR, { recursive: true });
  for (const zip of zips) {
    const target = join(RELEASE_DIR, `tether-extension-${version}-chrome-mv3.zip`);
    cpSync(join(outDir, zip), target);
    console.log(`extension artifact: ${relative(ROOT, target)}`);
  }
}

function packageDaemon(version: string): void {
  run('pnpm --filter @tether/daemon build', DAEMON_DIR);
  mkdirSync(join(RELEASE_DIR, 'daemon'), { recursive: true });
  cpSync(join(DAEMON_DIR, 'dist'), join(RELEASE_DIR, 'daemon'), { recursive: true });
  cpSync(join(DAEMON_DIR, 'package.json'), join(RELEASE_DIR, 'daemon', 'package.json'));

  if (hasBun()) {
    for (const t of BUN_TARGETS) {
      run(
        `bun build --compile --target=${t.target} src/index.ts --outfile ${join(RELEASE_DIR, t.name)}`,
        DAEMON_DIR,
      );
    }
    console.log('bun binaries embedded.');
    return;
  }

  writeFileSync(join(RELEASE_DIR, 'tether-daemon.mjs'), NODE_LAUNCHER, 'utf-8');
  writeFileSync(join(RELEASE_DIR, 'BINARIES.md'), BINARIES_MD(version), 'utf-8');
  console.log('bun not found — emitted tether-daemon.mjs launcher + BINARIES.md.');
}

function copyStoreAssets(): void {
  if (!existsSync(STORE_ASSETS)) {
    console.warn('no store assets dir — skipping (apps/web/public/store missing)');
    return;
  }
  cpSync(STORE_ASSETS, join(RELEASE_DIR, 'store'), { recursive: true });
  console.log('store assets copied to release/store/.');
}

function main(): void {
  const version = (
    JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf-8')) as {
      version: string;
    }
  ).version;

  rmSync(RELEASE_DIR, { recursive: true, force: true });
  mkdirSync(RELEASE_DIR, { recursive: true });

  packageExtension(version);
  packageDaemon(version);
  copyStoreAssets();
  writeManifest(version);
  console.log(`\nRelease v${version} packaged in ${relative(ROOT, RELEASE_DIR)}/`);
}

main();
